<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminappheader') ?>
<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>


    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Novo Utilizador</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('user/store')?>">
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->username?>" name="username" class="form-control" placeholder="Indique o Username">
                                    <?= ErrMgr::bind('username') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Nome <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->nome?>" name="nome" class="form-control" placeholder="Indique o Nome">
                                    <?= ErrMgr::bind('nome') ?>

                                </div>

                                <div class="top-margin">
                                    <label>Morada <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->morada?>" name="morada" class="form-control" placeholder="Indique a Morada">
                                    <?= ErrMgr::bind('morada') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->email?>" name="email" class="form-control" placeholder="Indique o Email">
                                    <?= ErrMgr::bind('email') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Numero de Indentificao Fiscal(NIF) <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->nif?>" name="nif" class="form-control" placeholder="Indique o NIF">
                                    <?= ErrMgr::bind('nif') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Telefone <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->telefone?>" name="telefone" class="form-control" placeholder="Indique o Telefone">
                                    <?= ErrMgr::bind('telefone') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Role <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$user->role?>" name="role" class="form-control" placeholder="Indique o Role">
                                    <?= ErrMgr::bind('role') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password" value="<?=$user->password?>" name="password" class="form-control" placeholder="Indique a Password">
                                    <?= ErrMgr::bind('password') ?>
                                </div>

                                <hr>

                                <div class="col-lg-5 text-right">
                                    <button class="btn btn-action" type="submit">Novo</button>
                                </div>
                                <div class="col-lg-5 text-right">
                                    <a href="<?=Url::toRoute('adminapp/gerirusers')?>">
                                        <button class="btn btn-danger" type="button">Cancelar</button>
                                    </a>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>