<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headeradmin') ?>
<?php $users = Data::get('users') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="<?= Url::toRoute('adminapp/index') ?>">Home</a></li>
            <li class="active">Gerir Utilizadores</li>
        </ol>

        <h2 class="text-left top-space">Lista de Utilizadores</h2>
        <h2 class="top-space"></h2>
        <div class="row"> <!-- /row -->
            <div class="col-sm-12">
                <table class="table table-striped">
                    <thead>
                    <th>
                        <h3>Id</h3>
                    </th>
                    <th>
                        <h3>Nome</h3>
                    </th>
                    <th>
                        <h3>Morada</h3>
                    </th>
                    <th>
                        <h3>Email</h3>
                    </th>
                    <th>
                        <h3>NIF</h3>
                    </th>
                    <th>
                        <h3>Telefone</h3>
                    </th>
                    <th>
                        <h3>Role</h3>
                    </th>
                    <th>
                        <h3>Opcoes</h3>
                    </th>
                    </thead>
                    <tbody>
                    <?php foreach ($users as $user) { ?>
                        <tr>
                            <td><?= $user->id ?></td>
                            <td><?= $user->nome ?></td>
                            <td><?= $user->morada ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->nif ?></td>
                            <td><?= $user->telefone ?></td>
                            <td><?= $user->role ?></td>
                            <td>
                                <a href="<?= Url::toRoute('user/edit', $user->id) ?>" class="btn btn-info"
                                   role="button">Edit</a>
                                <a href="<?= Url::toRoute('user/destroy', $user->id) ?>" class="btn btn-warning"
                                   role="button">Delete</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Criar um novo utilizador</h3>
                <p>
                    <a href="<?= Url::toRoute('user/create') ?>" class="btn btn-info" role="button">Novo</a>
                </p>
            </div>
        </div> <!-- /row -->
    </div>    <!-- /container -->

<?php Layout::includeLayout('footer') ?>