<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('users')?>
<?php ErrMgr::attach($users) ?>


    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">New Book</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?=Url::toRoute('finance/store')?>">
                                <div class="top-margin">
                                    <label>Descricao <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$finance->descricao?>" name="descricao" class="form-control" placeholder="Enter Description">
                                    <?= ErrMgr::bind('descricao') ?>

                                </div>
                                <div class="top-margin">
                                    <label>Tipo Categoria <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$finance->tipocategoria?>" name="tipocategoria" class="form-control" placeholder="Enter the type">
                                    <?= ErrMgr::bind('tipocategoria') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Data <span class="text-danger">*</span></label>
                                    <input type="data" value="<?=$finance->data?>" name="data" class="form-control" placeholder="Enter data">
                                    <?= ErrMgr::bind('data') ?>
                                </div>

                                <div class="top-margin">
                                    <label>ISBN <span class="text-danger">*</span></label>
                                    <input type="valor" value="<?=$finance->valor?>" name="valor" class="form-control" placeholder="Enter value">
                                    <?= ErrMgr::bind('valor') ?>
                                </div>

                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">New</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>