<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headeradmin') ?>
<?php $users = Data::get('users') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">User Index</li>
        </ol>

        <h2 class="text-left top-space">User Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Name</h3></th><th><h3>Role</h3></th><th><h3>User Actions</h3></th></thead>
                <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                    <td><?=$user->id?></td>
                    <td><?=$user->nome?></td>
                    <td><?=$user->role?></td>
                    <td>
                        <a href="<?=Url::toRoute('adminapp/edit', $user->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('adminapp/destroy', $user->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

            </div>
            <div class="col-sm-6">
                <h3>Criar um novo utilizador</h3>
                <p>
                    <a href="<?=Url::toRoute('adminapp/create')?>" class="btn btn-info" role="button">Novo</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>