<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headeradmin') ?>
<?php $aeroporto = Data::get('aeroporto') ?>
<?php ErrMgr::attach($aeroporto) ?>


<!-- container -->
<div class="container">

    <!-- row -->
    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">

            <header class="page-header">
                <h1 class="page-title">Novo Aeroporto</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?= Url::toRoute('aeroporto/store') ?>">
                            <div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $aeroporto->nome ?>" name="nome" class="form-control"
                                    placeholder="Nome do Aeroporto">
                                <?= ErrMgr::bind('nome') ?>
                            </div>

                            <div class="top-margin">
                                <label>Localização <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $aeroporto->localizacao ?>" name="localizacao"
                                    class="form-control" placeholder="Localização do Aeroporto">
                                <?= ErrMgr::bind('localizacao') ?>
                            </div>

                            <hr>

                            <div class="col-lg-5 text-right">
                                <button class="btn btn-action" type="submit">Novo</button>
                            </div>
                            <div class="col-lg-5 text-right">
                                <a href="<?= Url::toRoute('aeroporto/index') ?>">
                                    <button class="btn btn-danger" type="button">Cancelar</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article> <!-- /Article -->
    </div> <!-- /row -->
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>