<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headergestorvoo'); ?>
<?php $voo = Data::get('voo'); ?>
<?php ErrMgr::attach($voo) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Novo Voo</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?= Url::toRoute('voo/store') ?>">
                            <div class="top-margin">
                                <label>Preco Venda <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $voo->precovenda ?>" name="precovenda"
                                    class="form-control" placeholder="Preco Venda">
                                <?= ErrMgr::bind('precovenda') ?>
                            </div>
                            <hr>

                            <div class="col-lg-5 text-right">
                                <button class="btn btn-action" type="submit">Novo</button>
                            </div>
                            <div class="col-lg-5 text-right">
                                <a href="<?= Url::toRoute('voo/index') ?>">
                                    <button class="btn btn-danger" type="button">Cancelar</button>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>

    </article>
    <!-- /Article -->

</div>
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>