<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('gestorvooheader'); ?>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Bem Vindo - Gestor de Voo</b><br><small>Pode gerir aqui os Aviões, Voos e as Escalas.</small><br></h1>
            </div>
        </div>
    </header>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>