<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('headergestorvoo'); ?>
<?php
    //$users = Data::get('users');
    //$aeroportos = Data::get('aeroportos');
?>

<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Bem Vindo - Gestor Voos</b>
                <br><small>Pode gerir aqui os Voos, Escalas e Aviões.</small><br>
            </h1>
        </div>
    </div>
</header>
<!-- /Header -->

<!-- container -->
<div class="container">

    <h2 class="text-left top-space">Lista de Aeroportos</h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <th>
                        <h3>Id</h3>
                    </th>
                    <th>
                        <h3>Nome</h3>
                    </th>
                    <th>
                        <h3>Localização</h3>
                    </th>
                </thead>
                <tbody>
                    <?php  /*foreach ($aeroportos as $aeroporto) { ?>
                    <tr>
                        <td><?=$aeroporto->idaeroporto?></td>
                        <td><?=$aeroporto->nome?></td>
                        <td><?=$aeroporto->localizacao?></td>
                    </tr>
                    <?php } */?>

                </tbody>
            </table>
        </div>
    </div> <!-- /row -->

</div> <!-- /container -->

<?php Layout::includeLayout('footer')?>