<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headeradmin') ?>
<?php $aeroporto = Data::get('aeroporto') ?>
<?php ErrMgr::attach($aeroporto) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Editar Aeroporto</h1>
				</header>
				

					<div class="panel panel-default">
						<div class="panel-body">

                            <hr>

							<form class="form-horizontal" method="post" action="<?=Url::toRoute('adminapp/updateaeroporto', $aeroporto->idaeroporto)?>">

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Nome:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" value="<?=$aeroporto->nome?>" class="form-control" required name="nome" placeholder="Nome do Aeroporto">
                                        <?= ErrMgr::bind('nome') ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="localizacao">Localização:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$aeroporto->localizacao?>" class="form-control" name="localizacao" placeholder="Localização do Aeroporto">
                                        <?= ErrMgr::bind('localizacao') ?>
                                    </div>
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-default" type="submit">Salvar</button>
									</div>
								</div>
							</form>
						</div>
					</div>


				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>