<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headeradmin') ?>
<?php $aeroportos = Data::get('aeroportos') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Gerir Aeroportos</li>
        </ol>

        <h2 class="text-left top-space">Lista de Aeroportos</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Nome</h3></th><th><h3>Localização</h3></th><th><h3>Acoes</h3></th></thead>
                <tbody>
                <?php foreach ($aeroportos as $aeroporto) { ?>
                    <tr>
                    <td><?=$aeroporto->idaeroporto?></td>
                    <td><?=$aeroporto->nome?></td>
                    <td><?=$aeroporto->localizacao?></td>
                    <td>
                        <a href="<?=Url::toRoute('adminapp/editaeroporto', $aeroporto->idaeroporto)?>" class="btn btn-info" role="button">Editar</a>
                        <a href="<?=Url::toRoute('adminapp/destroyaeroporto', $aeroporto->idaeroporto)?>" class="btn btn-warning" role="button">Apagar</a>
                    </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

            </div>
            <div class="col-sm-6">
                <h3>Criar novo Aeroporto</h3>
                <p>
                    <a href="<?=Url::toRoute('adminapp/createaeroporto')?>" class="btn btn-info" role="button">Novo</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>