
<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-5 widget">
                    <h3 class="widget-title">MVC Utilizada:</h3>
                    <div class="widget-body">
                        <p>
                            WebLogicMVCby<br>
                            Silvio Mendes<br>
                            <a href="mailto:#">smendes@ipleiria.pt</a><br>
                        </p>
                    </div>
                </div>

                <div class="col-mg-5 widget">
                    <h3 class="widget-title">Projeto de Programacao para Web - Servidor</h3>
                    <div class="widget-body">
                        <p>
                            Realizado por:<br><br>
                            Artur Quaresma - 2201115<br>
                            Marcelo Marques - 2200428<br>
                            Vasco Silva - 2200426<br>
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

<div class="footer2">
    <div class="container">
        <div class="row">

            <div class="col-md-6 widget">
                <div class="widget-body">
                    <p>
                        Copyright &copy; 2016-2021, Silvio Priem Mendes, PhD. <br> Site template by Sergey Pozhilov.
                    </p>
                </div>
            </div>

        </div> <!-- /row of widgets -->
    </div>
</div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?= AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>