<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Flight Travel Air</b></h1>
                <h2>Getting the best flights for you, everyday!</h2>
                <h3>Just register and find unlimited travel and flight options.</h3>
            </div>
        </div>
    </header>
    <!-- /Header -->


    <!-- Intro -->
    <div class="container text-center">
        <h2 class="thin">Find the Perfect Flight Here . . . And Go Everywhere.</h2>
        <br>
        <h4>We try to offer the best available flights!</h4>
    </div>
    <!-- /Intro-->

<?php Layout::includeLayout('footer')?>