<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('headerpassageiro'); ?>

<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Bem Vindo - Passageiro</b>
                <br><small>Pode consultar, reservar e comprar bilhetes para Voos.</small><br>
            </h1>
        </div>
    </div>
</header>
<!-- /Header -->

<!-- container  Aviões -->
<div class="container">
    <h1>Não implementado de momento. :(</h1>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer')?>