<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('headergestorvoo'); ?>
<?php $avioes = Data::get('avioes') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?= Url::toRoute('gestorvooapp/index') ?>">Home</a></li>
        <li class="active">Gerir Aviões</li>
    </ol>

    <h2 class="text-left top-space">Lista de Aviões</h2>
    <h2 class="top-space"></h2>

    <!-- row -->
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <th>
                        <h3>Id</h3>
                    </th>
                    <th>
                        <h3>Referencia</h3>
                    </th>
                    <th>
                        <h3>Lotacao</h3>
                    </th>
                    <th>
                        <h3>Tipo Avião</h3>
                    </th>
                </thead>
                <tbody>
                    <?php foreach ($avioes as $aviao) { ?>
                    <tr>
                        <td><?= $aviao->idaviao ?></td>
                        <td><?= $aviao->referencia ?></td>
                        <td><?= $aviao->lotacao ?></td>
                        <td><?= $aviao->tipoaviao ?></td>
                        <td>
                            <a href="<?= Url::toRoute('aviao/edit', $aviao->idaviao) ?>" class="btn btn-info"
                                role="button">Editar</a>
                            <a href="<?= Url::toRoute('aviao/destroy', $aviao->idaviao) ?>" class="btn btn-warning"
                                role="button">Apagar</a>
                        </td>
                    </tr>
                    <?php } ?>

                </tbody>

            </table>
        </div>

        <div class="col-sm-6">
            <h3>Criar novo Avião</h3>
            <p>
                <a href="<?= Url::toRoute('aviao/create') ?>" class="btn btn-info" role="button">Novo</a>
            </p>
        </div>
    </div> <!-- /row -->
</div> <!-- /container -->

<?php Layout::includeLayout('footer') ?>