<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('opcheckinheader'); ?>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Bem Vindo - Operador de Checkin</b><br><small>Pode realizar aqui o Checkin de Passageiros e visualizar os Detalhes de Voo.</small><br></h1>
            </div>
        </div>
    </header>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>